// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM user_schema.profiles WHERE username = $1
) AS exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO user_schema.profiles (id, display_name, username, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, display_name, username, avatar_url, bio, last_seen_at, is_active, created_at, updated_at
`

type CreateProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Username    string    `json:"username"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (UserSchemaProfile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.ID, arg.DisplayName, arg.Username)
	var i UserSchemaProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProfile = `-- name: DeactivateProfile :exec
UPDATE user_schema.profiles
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateProfile, id)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, display_name, username, avatar_url, bio, last_seen_at, is_active, created_at, updated_at FROM user_schema.profiles
WHERE id = $1 AND is_active = true
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (UserSchemaProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i UserSchemaProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT id, display_name, username, avatar_url, bio, last_seen_at, is_active, created_at, updated_at FROM user_schema.profiles
WHERE username = $1 AND is_active = true
`

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (UserSchemaProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUsername, username)
	var i UserSchemaProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfilesByIDs = `-- name: GetProfilesByIDs :many
SELECT id, display_name, username, avatar_url, bio, last_seen_at, is_active, created_at, updated_at FROM user_schema.profiles
WHERE id = ANY($1::uuid[]) AND is_active = true
`

func (q *Queries) GetProfilesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]UserSchemaProfile, error) {
	rows, err := q.db.Query(ctx, getProfilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSchemaProfile{}
	for rows.Next() {
		var i UserSchemaProfile
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.LastSeenAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProfiles = `-- name: SearchProfiles :many
SELECT id, display_name, username, avatar_url, bio, last_seen_at, is_active, created_at, updated_at FROM user_schema.profiles
WHERE is_active = true
  AND (
      display_name ILIKE '%' || $3::text || '%'
      OR username ILIKE '%' || $3::text || '%'
  )
ORDER BY
    CASE
        WHEN username = $3::text THEN 0
        WHEN username ILIKE $3::text || '%' THEN 1
        WHEN display_name ILIKE $3::text || '%' THEN 2
        ELSE 3
    END,
    created_at DESC
LIMIT $1 OFFSET $2
`

type SearchProfilesParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Query  string `json:"query"`
}

func (q *Queries) SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]UserSchemaProfile, error) {
	rows, err := q.db.Query(ctx, searchProfiles, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSchemaProfile{}
	for rows.Next() {
		var i UserSchemaProfile
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.AvatarUrl,
			&i.Bio,
			&i.LastSeenAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastSeen = `-- name: UpdateLastSeen :exec
UPDATE user_schema.profiles
SET last_seen_at = NOW()
WHERE id = $1 AND is_active = true
`

func (q *Queries) UpdateLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateLastSeen, id)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE user_schema.profiles
SET
    display_name = COALESCE($2, display_name),
    username     = COALESCE($3, username),
    avatar_url   = COALESCE($4, avatar_url),
    bio          = COALESCE($5, bio),
    updated_at   = NOW()
WHERE id = $1 AND is_active = true
RETURNING id, display_name, username, avatar_url, bio, last_seen_at, is_active, created_at, updated_at
`

type UpdateProfileParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName *string   `json:"display_name"`
	Username    *string   `json:"username"`
	AvatarUrl   *string   `json:"avatar_url"`
	Bio         *string   `json:"bio"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UserSchemaProfile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.DisplayName,
		arg.Username,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i UserSchemaProfile
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
